nelmio_cors:
  defaults:
    allow_origin: ['*']                # ou ['http://localhost:4200']
    allow_headers: ['Content-Type','Authorization']
    allow_methods: ['GET','POST','PUT','DELETE','OPTIONS']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_headers: ['Content-Type','Authorization']
      allow_methods: ['GET','POST','PUT','DELETE','OPTIONS']
      max_age: 3600
